# Generated by Django 5.2.4 on 2025-08-10 17:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('CUSTOMER_SERVICE', 'Customer Service'), ('DELIVERY', 'Delivery')], max_length=20, unique=True)),
                ('can_view_orders', models.BooleanField(default=True)),
                ('can_edit_order_items', models.BooleanField(default=False)),
                ('can_update_status', models.BooleanField(default=False)),
                ('can_assign_orders', models.BooleanField(default=False)),
                ('can_view_customer_info', models.BooleanField(default=True)),
                ('can_view_financials', models.BooleanField(default=False)),
                ('can_process_refunds', models.BooleanField(default=False)),
                ('can_manage_returns', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Order Permission',
                'verbose_name_plural': 'Order Permissions',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PROCESSING', 'Processing'), ('READY_FOR_SHIPMENT', 'Ready for Shipment'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_RECEIVED', 'Return Received'), ('REFUNDED', 'Refunded'), ('ON_HOLD', 'On Hold'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CHAPA', 'Chapa'), ('CASH_ON_DELIVERY', 'Cash on Delivery'), ('BANK_TRANSFER', 'Bank Transfer'), ('WALLET', 'Wallet')], max_length=20, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_notes', models.TextField(blank=True, help_text='Notes from the customer')),
                ('vendor_notes', models.TextField(blank=True, help_text='Internal notes for vendor')),
                ('admin_notes', models.TextField(blank=True, help_text='Notes for administrators')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Vendor employee currently handling this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='Users.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders', to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='Users.address')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_orders', to='Users.vendor')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'permissions': [('view_all_orders', 'Can view all orders (Admin)'), ('view_vendor_orders', 'Can view vendor orders'), ('change_order_status', 'Can change order status'), ('assign_order', 'Can assign orders to employees')],
            },
        ),
        migrations.CreateModel(
            name='OrderAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_order_history', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Assignment',
                'verbose_name_plural': 'Order Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vendor_notes', models.TextField(blank=True, help_text='Internal notes for vendor')),
                ('admin_notes', models.TextField(blank=True, help_text='Notes for administrators')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PROCESSING', 'Processing'), ('READY_FOR_SHIPMENT', 'Ready for Shipment'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_RECEIVED', 'Return Received'), ('REFUNDED', 'Refunded'), ('ON_HOLD', 'On Hold'), ('FAILED', 'Failed')], max_length=20)),
                ('new_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PROCESSING', 'Processing'), ('READY_FOR_SHIPMENT', 'Ready for Shipment'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_RECEIVED', 'Return Received'), ('REFUNDED', 'Refunded'), ('ON_HOLD', 'On Hold'), ('FAILED', 'Failed')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorOrderAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_items_sold', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_analytics', to='Users.vendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor Order Analytics',
            },
        ),
        migrations.CreateModel(
            name='VendorOrderDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_status_filter', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PROCESSING', 'Processing'), ('READY_FOR_SHIPMENT', 'Ready for Shipment'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_RECEIVED', 'Return Received'), ('REFUNDED', 'Refunded'), ('ON_HOLD', 'On Hold'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('show_unassigned_orders', models.BooleanField(default=True)),
                ('show_assigned_to_others', models.BooleanField(default=False)),
                ('notify_new_orders', models.BooleanField(default=True)),
                ('notify_assigned_orders', models.BooleanField(default=True)),
                ('notify_status_changes', models.BooleanField(default=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Order Dashboard',
                'verbose_name_plural': 'Vendor Order Dashboards',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='orders_orde_custome_c9b64a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['vendor', 'status'], name='orders_orde_vendor__d2c878_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_to', 'status'], name='orders_orde_assigne_6abf64_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'status_changed_at'], name='orders_orde_status_9a3821_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='orders_orde_order_i_52f79a_idx'),
        ),
    ]
