# Generated by Django 5.2.4 on 2025-08-10 18:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vendoremployee',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user_email',
        ),
        migrations.RemoveConstraint(
            model_name='vendoremployee',
            name='unique_employee_id',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_last_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendoremployee',
            name='vendor_employee_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendoremployee',
            name='employee_role_active_idx',
        ),
        migrations.RemoveField(
            model_name='vendoremployee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vendoremployee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='vendoremployee',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='vendoremployee',
            name='termination_date',
        ),
        migrations.RemoveField(
            model_name='vendoremployee',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('VENDOR_STAFF', 'Vendor Staff')], default='CUSTOMER', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vendoremployee',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vendoremployee',
            name='hire_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vendoremployee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vendoremployee',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('DELIVERY', 'Delivery'), ('CUSTOMER_SERVICE', 'Customer Service')], default='STAFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendoremployee',
            name='user',
            field=models.OneToOneField(help_text='User account associated with this employee', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='vendoremployee',
            index=models.Index(fields=['vendor'], name='vendor_employee_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='vendoremployee',
            index=models.Index(fields=['is_active'], name='employee_active_idx'),
        ),
    ]
