# Generated by Django 5.0.1 on 2025-12-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_kycdocument_kycverification_loginattempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('vendor', 'Vendor'), ('buyer', 'Buyer')], default='buyer', max_length=15),
        ),
        migrations.DeleteModel(
            name='KYCDocument',
        ),
        migrations.DeleteModel(
            name='KYCVerification',
        ),
    ]
