# Generated by Django 5.0.1 on 2025-11-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='additional_document',
            field=models.FileField(blank=True, help_text='Any additional supporting document', null=True, upload_to='vendor_documents/additional/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_statement',
            field=models.FileField(blank=True, help_text='Recent bank statement', null=True, upload_to='vendor_documents/bank/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_license',
            field=models.FileField(blank=True, help_text='Business license or registration certificate', null=True, upload_to='vendor_documents/licenses/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='id_document',
            field=models.FileField(blank=True, help_text="Owner's ID or passport", null=True, upload_to='vendor_documents/ids/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='office_address',
            field=models.TextField(blank=True, help_text='Physical office address'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='office_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='office_country',
            field=models.CharField(default='Ethiopia', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='office_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='office_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='tax_certificate',
            field=models.FileField(blank=True, help_text='Tax registration certificate', null=True, upload_to='vendor_documents/tax/'),
        ),
    ]
