# Generated by Django 5.0.1 on 2025-11-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorprofile_additional_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='telegram_url',
            field=models.URLField(blank=True, help_text='Telegram channel/group URL', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='X.com (Twitter) profile URL', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text='Business website URL', max_length=255),
        ),
    ]
