# Generated by Django 5.0.1 on 2025-11-29 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorprofile_facebook_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Account active status'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='suspended_at',
            field=models.DateTimeField(blank=True, help_text='When account was suspended', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for suspension'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_name',
            field=models.CharField(blank=True, default='', help_text='Owner/Contact person name', max_length=255),
        ),
    ]
