# Generated by Django 5.0.1 on 2025-12-16 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorprofile_latitude_vendorprofile_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='office_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='office_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='office_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='office_postal_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='office_state',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='additional_document',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='bank_statement',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='business_license',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='tax_certificate',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='verification_notes',
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='telegram_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='website_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_verifications',
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('identity', 'Identity Document'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('proof_of_address', 'Proof of Address'), ('business_license', 'Business License'), ('tax_certificate', 'Tax Certificate'), ('bank_statement', 'Bank Statement'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='kyc_documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.kycverification')),
            ],
            options={
                'db_table': 'kyc_documents',
            },
        ),
        migrations.AddIndex(
            model_name='kycverification',
            index=models.Index(fields=['status'], name='kyc_verific_status_0b0fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='kycverification',
            index=models.Index(fields=['submitted_at'], name='kyc_verific_submitt_6e810c_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['kyc', 'document_type'], name='kyc_documen_kyc_id_8bb0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['uploaded_at'], name='kyc_documen_uploade_c18557_idx'),
        ),
    ]
