# Generated by Django 5.0.1 on 2025-11-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('products', '0002_product_status'),
    ]

    operations = [
    ]
