# Generated by Django 5.0.1 on 2025-12-01 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_0002_initial_0002_product_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_status_a30e64_idx',
            old_name='products_status_idx',
        ),
    ]
